export const EnterEditingRoadConnectionLaneItemEvent = "road_connection_lane_editor_enter_editing_road_connection_lane_item";

export const ExitEditingRoadConnectionLaneItemEvent = "road_connection_lane_editor_exit_editing_road_connection_lane_item";

export const PickConnectionLaneActionMeshEvent = "road_connection_lane_editor_pick_connection_lane_action_mesh";

export const OperateConnectionLaneActionMeshEvent = "road_connection_lane_editor_operate_connection_lane_action_mesh";

export const UnpickConnectionLaneActionMeshEvent = "road_connection_lane_editor_unpick_connection_lane_action_mesh";

export const PickPrevAndNextConnectionLaneVertexEvent = "road_connection_lane_editor_pick_prev_and_next_connection_lane_vertex";

export const CleanPickedPrevAndNextConnectionLaneVertexEvent = "road_connection_lane_editor_clean_picked_prev_and_next_connection_lane_vertex";

export const DeliverRoadConnectionLaneInnerAddCatmullPointEvent = "road_Connection_lane_editor_deliver_road_Connection_lane_inner_add_catmull_point";

export const DeliverRoadConnectionLaneInnerRemoveCatmullPointEvent = "road_Connection_lane_editor_deliver_road_Connection_lane_inner_remove_catmull_point";