// This Source Code Form is subject to the terms of the Mozilla Public
// License, v2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/

/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.1
 * source: map/map_pnc_junction.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";

import * as dependency_2 from "./map_geometry";
import * as dependency_1 from "./map_id";

export namespace atlas.hdmap {
  export class Passage extends pb_1.Message {
    constructor(
      data?:
        | any[]
        | {
            id?: dependency_1.atlas.hdmap.Id;
            signal_id: dependency_1.atlas.hdmap.Id[];
            yield_id: dependency_1.atlas.hdmap.Id[];
            stop_sign_id: dependency_1.atlas.hdmap.Id[];
            lane_id: dependency_1.atlas.hdmap.Id[];
            type?: Passage.Type;
          },
    ) {
      super();
      pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2, 3, 4, 5], []);
      if (!Array.isArray(data) && typeof data == "object") {
        if ("id" in data && data.id != undefined) {
          this.id = data.id;
        }
        this.signal_id = data.signal_id;
        this.yield_id = data.yield_id;
        this.stop_sign_id = data.stop_sign_id;
        this.lane_id = data.lane_id;
        if ("type" in data && data.type != undefined) {
          this.type = data.type;
        }
      }
    }
    get id() {
      return pb_1.Message.getWrapperField(this, dependency_1.atlas.hdmap.Id, 1);
    }
    set id(value: dependency_1.atlas.hdmap.Id) {
      pb_1.Message.setWrapperField(this, 1, value);
    }
    get signal_id() {
      return pb_1.Message.getRepeatedWrapperField(this, dependency_1.atlas.hdmap.Id, 2);
    }
    set signal_id(value: dependency_1.atlas.hdmap.Id[]) {
      pb_1.Message.setRepeatedWrapperField(this, 2, value);
    }
    get yield_id() {
      return pb_1.Message.getRepeatedWrapperField(this, dependency_1.atlas.hdmap.Id, 3);
    }
    set yield_id(value: dependency_1.atlas.hdmap.Id[]) {
      pb_1.Message.setRepeatedWrapperField(this, 3, value);
    }
    get stop_sign_id() {
      return pb_1.Message.getRepeatedWrapperField(this, dependency_1.atlas.hdmap.Id, 4);
    }
    set stop_sign_id(value: dependency_1.atlas.hdmap.Id[]) {
      pb_1.Message.setRepeatedWrapperField(this, 4, value);
    }
    get lane_id() {
      return pb_1.Message.getRepeatedWrapperField(this, dependency_1.atlas.hdmap.Id, 5);
    }
    set lane_id(value: dependency_1.atlas.hdmap.Id[]) {
      pb_1.Message.setRepeatedWrapperField(this, 5, value);
    }
    get type() {
      return pb_1.Message.getField(this, 6) as Passage.Type;
    }
    set type(value: Passage.Type) {
      pb_1.Message.setField(this, 6, value);
    }
    static fromObject(data: {
      id?: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>;
      signal_id: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>[];
      yield_id: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>[];
      stop_sign_id: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>[];
      lane_id: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>[];
      type?: Passage.Type;
    }) {
      const message = new Passage({
        signal_id: data.signal_id.map((item) => dependency_1.atlas.hdmap.Id.fromObject(item)),
        yield_id: data.yield_id.map((item) => dependency_1.atlas.hdmap.Id.fromObject(item)),
        stop_sign_id: data.stop_sign_id.map((item) => dependency_1.atlas.hdmap.Id.fromObject(item)),
        lane_id: data.lane_id.map((item) => dependency_1.atlas.hdmap.Id.fromObject(item)),
      });
      if (data.id != null) {
        message.id = dependency_1.atlas.hdmap.Id.fromObject(data.id);
      }
      if (data.type != null) {
        message.type = data.type;
      }
      return message;
    }
    toObject() {
      const data: {
        id?: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>;
        signal_id: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>[];
        yield_id: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>[];
        stop_sign_id: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>[];
        lane_id: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>[];
        type?: Passage.Type;
      } = {
        signal_id: this.signal_id.map((item: dependency_1.atlas.hdmap.Id) => item.toObject()),
        yield_id: this.yield_id.map((item: dependency_1.atlas.hdmap.Id) => item.toObject()),
        stop_sign_id: this.stop_sign_id.map((item: dependency_1.atlas.hdmap.Id) => item.toObject()),
        lane_id: this.lane_id.map((item: dependency_1.atlas.hdmap.Id) => item.toObject()),
      };
      if (this.id != null) {
        data.id = this.id.toObject();
      }
      if (this.type != null) {
        data.type = this.type;
      }
      return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
      const writer = w || new pb_1.BinaryWriter();
      if (this.id !== undefined) {
        writer.writeMessage(1, this.id, () => this.id.serialize(writer));
      }
      if (this.signal_id !== undefined) {
        writer.writeRepeatedMessage(2, this.signal_id, (item: dependency_1.atlas.hdmap.Id) =>
          item.serialize(writer),
        );
      }
      if (this.yield_id !== undefined) {
        writer.writeRepeatedMessage(3, this.yield_id, (item: dependency_1.atlas.hdmap.Id) =>
          item.serialize(writer),
        );
      }
      if (this.stop_sign_id !== undefined) {
        writer.writeRepeatedMessage(4, this.stop_sign_id, (item: dependency_1.atlas.hdmap.Id) =>
          item.serialize(writer),
        );
      }
      if (this.lane_id !== undefined) {
        writer.writeRepeatedMessage(5, this.lane_id, (item: dependency_1.atlas.hdmap.Id) =>
          item.serialize(writer),
        );
      }
      if (this.type !== undefined) {
        writer.writeEnum(6, this.type);
      }
      if (!w) {
        return writer.getResultBuffer();
      }
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Passage {
      const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes),
        message = new Passage();
      while (reader.nextField()) {
        if (reader.isEndGroup()) {
          break;
        }
        switch (reader.getFieldNumber()) {
          case 1:
            reader.readMessage(
              message.id,
              () => (message.id = dependency_1.atlas.hdmap.Id.deserialize(reader)),
            );
            break;
          case 2:
            reader.readMessage(message.signal_id, () =>
              pb_1.Message.addToRepeatedWrapperField(
                message,
                2,
                dependency_1.atlas.hdmap.Id.deserialize(reader),
                dependency_1.atlas.hdmap.Id,
              ),
            );
            break;
          case 3:
            reader.readMessage(message.yield_id, () =>
              pb_1.Message.addToRepeatedWrapperField(
                message,
                3,
                dependency_1.atlas.hdmap.Id.deserialize(reader),
                dependency_1.atlas.hdmap.Id,
              ),
            );
            break;
          case 4:
            reader.readMessage(message.stop_sign_id, () =>
              pb_1.Message.addToRepeatedWrapperField(
                message,
                4,
                dependency_1.atlas.hdmap.Id.deserialize(reader),
                dependency_1.atlas.hdmap.Id,
              ),
            );
            break;
          case 5:
            reader.readMessage(message.lane_id, () =>
              pb_1.Message.addToRepeatedWrapperField(
                message,
                5,
                dependency_1.atlas.hdmap.Id.deserialize(reader),
                dependency_1.atlas.hdmap.Id,
              ),
            );
            break;
          case 6:
            message.type = reader.readEnum();
            break;
          default:
            reader.skipField();
        }
      }
      return message;
    }
    serializeBinary(): Uint8Array {
      return this.serialize();
    }
    static override deserializeBinary(bytes: Uint8Array): Passage {
      return Passage.deserialize(bytes);
    }
  }
  export namespace Passage {
    export enum Type {
      UNKNOWN = 0,
      ENTRANCE = 1,
      EXIT = 2,
    }
  }
  export class PassageGroup extends pb_1.Message {
    constructor(
      data?:
        | any[]
        | {
            id?: dependency_1.atlas.hdmap.Id;
            passage: Passage[];
          },
    ) {
      super();
      pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], []);
      if (!Array.isArray(data) && typeof data == "object") {
        if ("id" in data && data.id != undefined) {
          this.id = data.id;
        }
        this.passage = data.passage;
      }
    }
    get id() {
      return pb_1.Message.getWrapperField(this, dependency_1.atlas.hdmap.Id, 1);
    }
    set id(value: dependency_1.atlas.hdmap.Id) {
      pb_1.Message.setWrapperField(this, 1, value);
    }
    get passage() {
      return pb_1.Message.getRepeatedWrapperField(this, Passage, 2);
    }
    set passage(value: Passage[]) {
      pb_1.Message.setRepeatedWrapperField(this, 2, value);
    }
    static fromObject(data: {
      id?: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>;
      passage: ReturnType<typeof Passage.prototype.toObject>[];
    }) {
      const message = new PassageGroup({
        passage: data.passage.map((item) => Passage.fromObject(item)),
      });
      if (data.id != null) {
        message.id = dependency_1.atlas.hdmap.Id.fromObject(data.id);
      }
      return message;
    }
    toObject() {
      const data: {
        id?: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>;
        passage: ReturnType<typeof Passage.prototype.toObject>[];
      } = {
        passage: this.passage.map((item: Passage) => item.toObject()),
      };
      if (this.id != null) {
        data.id = this.id.toObject();
      }
      return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
      const writer = w || new pb_1.BinaryWriter();
      if (this.id !== undefined) {
        writer.writeMessage(1, this.id, () => this.id.serialize(writer));
      }
      if (this.passage !== undefined) {
        writer.writeRepeatedMessage(2, this.passage, (item: Passage) => item.serialize(writer));
      }
      if (!w) {
        return writer.getResultBuffer();
      }
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PassageGroup {
      const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes),
        message = new PassageGroup();
      while (reader.nextField()) {
        if (reader.isEndGroup()) {
          break;
        }
        switch (reader.getFieldNumber()) {
          case 1:
            reader.readMessage(
              message.id,
              () => (message.id = dependency_1.atlas.hdmap.Id.deserialize(reader)),
            );
            break;
          case 2:
            reader.readMessage(message.passage, () =>
              pb_1.Message.addToRepeatedWrapperField(
                message,
                2,
                Passage.deserialize(reader),
                Passage,
              ),
            );
            break;
          default:
            reader.skipField();
        }
      }
      return message;
    }
    serializeBinary(): Uint8Array {
      return this.serialize();
    }
    static override deserializeBinary(bytes: Uint8Array): PassageGroup {
      return PassageGroup.deserialize(bytes);
    }
  }
  export class PNCJunction extends pb_1.Message {
    constructor(
      data?:
        | any[]
        | {
            id?: dependency_1.atlas.hdmap.Id;
            polygon?: dependency_2.atlas.hdmap.Polygon;
            overlap_id: dependency_1.atlas.hdmap.Id[];
            passage_group: PassageGroup[];
          },
    ) {
      super();
      pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [3, 4], []);
      if (!Array.isArray(data) && typeof data == "object") {
        if ("id" in data && data.id != undefined) {
          this.id = data.id;
        }
        if ("polygon" in data && data.polygon != undefined) {
          this.polygon = data.polygon;
        }
        this.overlap_id = data.overlap_id;
        this.passage_group = data.passage_group;
      }
    }
    get id() {
      return pb_1.Message.getWrapperField(this, dependency_1.atlas.hdmap.Id, 1);
    }
    set id(value: dependency_1.atlas.hdmap.Id) {
      pb_1.Message.setWrapperField(this, 1, value);
    }
    get polygon() {
      return pb_1.Message.getWrapperField(this, dependency_2.atlas.hdmap.Polygon, 2);
    }
    set polygon(value: dependency_2.atlas.hdmap.Polygon) {
      pb_1.Message.setWrapperField(this, 2, value);
    }
    get overlap_id() {
      return pb_1.Message.getRepeatedWrapperField(this, dependency_1.atlas.hdmap.Id, 3);
    }
    set overlap_id(value: dependency_1.atlas.hdmap.Id[]) {
      pb_1.Message.setRepeatedWrapperField(this, 3, value);
    }
    get passage_group() {
      return pb_1.Message.getRepeatedWrapperField(this, PassageGroup, 4);
    }
    set passage_group(value: PassageGroup[]) {
      pb_1.Message.setRepeatedWrapperField(this, 4, value);
    }
    static fromObject(data: {
      id?: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>;
      polygon?: ReturnType<typeof dependency_2.atlas.hdmap.Polygon.prototype.toObject>;
      overlap_id: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>[];
      passage_group: ReturnType<typeof PassageGroup.prototype.toObject>[];
    }) {
      const message = new PNCJunction({
        overlap_id: data.overlap_id.map((item) => dependency_1.atlas.hdmap.Id.fromObject(item)),
        passage_group: data.passage_group.map((item) => PassageGroup.fromObject(item)),
      });
      if (data.id != null) {
        message.id = dependency_1.atlas.hdmap.Id.fromObject(data.id);
      }
      if (data.polygon != null) {
        message.polygon = dependency_2.atlas.hdmap.Polygon.fromObject(data.polygon);
      }
      return message;
    }
    toObject() {
      const data: {
        id?: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>;
        polygon?: ReturnType<typeof dependency_2.atlas.hdmap.Polygon.prototype.toObject>;
        overlap_id: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>[];
        passage_group: ReturnType<typeof PassageGroup.prototype.toObject>[];
      } = {
        overlap_id: this.overlap_id.map((item: dependency_1.atlas.hdmap.Id) => item.toObject()),
        passage_group: this.passage_group.map((item: PassageGroup) => item.toObject()),
      };
      if (this.id != null) {
        data.id = this.id.toObject();
      }
      if (this.polygon != null) {
        data.polygon = this.polygon.toObject();
      }
      return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
      const writer = w || new pb_1.BinaryWriter();
      if (this.id !== undefined) {
        writer.writeMessage(1, this.id, () => this.id.serialize(writer));
      }
      if (this.polygon !== undefined) {
        writer.writeMessage(2, this.polygon, () => this.polygon.serialize(writer));
      }
      if (this.overlap_id !== undefined) {
        writer.writeRepeatedMessage(3, this.overlap_id, (item: dependency_1.atlas.hdmap.Id) =>
          item.serialize(writer),
        );
      }
      if (this.passage_group !== undefined) {
        writer.writeRepeatedMessage(4, this.passage_group, (item: PassageGroup) =>
          item.serialize(writer),
        );
      }
      if (!w) {
        return writer.getResultBuffer();
      }
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PNCJunction {
      const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes),
        message = new PNCJunction();
      while (reader.nextField()) {
        if (reader.isEndGroup()) {
          break;
        }
        switch (reader.getFieldNumber()) {
          case 1:
            reader.readMessage(
              message.id,
              () => (message.id = dependency_1.atlas.hdmap.Id.deserialize(reader)),
            );
            break;
          case 2:
            reader.readMessage(
              message.polygon,
              () => (message.polygon = dependency_2.atlas.hdmap.Polygon.deserialize(reader)),
            );
            break;
          case 3:
            reader.readMessage(message.overlap_id, () =>
              pb_1.Message.addToRepeatedWrapperField(
                message,
                3,
                dependency_1.atlas.hdmap.Id.deserialize(reader),
                dependency_1.atlas.hdmap.Id,
              ),
            );
            break;
          case 4:
            reader.readMessage(message.passage_group, () =>
              pb_1.Message.addToRepeatedWrapperField(
                message,
                4,
                PassageGroup.deserialize(reader),
                PassageGroup,
              ),
            );
            break;
          default:
            reader.skipField();
        }
      }
      return message;
    }
    serializeBinary(): Uint8Array {
      return this.serialize();
    }
    static override deserializeBinary(bytes: Uint8Array): PNCJunction {
      return PNCJunction.deserialize(bytes);
    }
  }
}
