// This Source Code Form is subject to the terms of the Mozilla Public
// License, v2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/

/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.1
 * source: map/map_speed_bump.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";

import * as dependency_2 from "./map_geometry";
import * as dependency_1 from "./map_id";

export namespace atlas.hdmap {
  export class SpeedBump extends pb_1.Message {
    constructor(
      data?:
        | any[]
        | {
            id?: dependency_1.atlas.hdmap.Id;
            overlap_id: dependency_1.atlas.hdmap.Id[];
            position: dependency_2.atlas.hdmap.Curve[];
          },
    ) {
      super();
      pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2, 3], []);
      if (!Array.isArray(data) && typeof data == "object") {
        if ("id" in data && data.id != undefined) {
          this.id = data.id;
        }
        this.overlap_id = data.overlap_id;
        this.position = data.position;
      }
    }
    get id() {
      return pb_1.Message.getWrapperField(this, dependency_1.atlas.hdmap.Id, 1);
    }
    set id(value: dependency_1.atlas.hdmap.Id) {
      pb_1.Message.setWrapperField(this, 1, value);
    }
    get overlap_id() {
      return pb_1.Message.getRepeatedWrapperField(this, dependency_1.atlas.hdmap.Id, 2);
    }
    set overlap_id(value: dependency_1.atlas.hdmap.Id[]) {
      pb_1.Message.setRepeatedWrapperField(this, 2, value);
    }
    get position() {
      return pb_1.Message.getRepeatedWrapperField(this, dependency_2.atlas.hdmap.Curve, 3);
    }
    set position(value: dependency_2.atlas.hdmap.Curve[]) {
      pb_1.Message.setRepeatedWrapperField(this, 3, value);
    }
    static fromObject(data: {
      id?: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>;
      overlap_id: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>[];
      position: ReturnType<typeof dependency_2.atlas.hdmap.Curve.prototype.toObject>[];
    }) {
      const message = new SpeedBump({
        overlap_id: data.overlap_id.map((item) => dependency_1.atlas.hdmap.Id.fromObject(item)),
        position: data.position.map((item) => dependency_2.atlas.hdmap.Curve.fromObject(item)),
      });
      if (data.id != null) {
        message.id = dependency_1.atlas.hdmap.Id.fromObject(data.id);
      }
      return message;
    }
    toObject() {
      const data: {
        id?: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>;
        overlap_id: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>[];
        position: ReturnType<typeof dependency_2.atlas.hdmap.Curve.prototype.toObject>[];
      } = {
        overlap_id: this.overlap_id.map((item: dependency_1.atlas.hdmap.Id) => item.toObject()),
        position: this.position.map((item: dependency_2.atlas.hdmap.Curve) => item.toObject()),
      };
      if (this.id != null) {
        data.id = this.id.toObject();
      }
      return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
      const writer = w || new pb_1.BinaryWriter();
      if (this.id !== undefined) {
        writer.writeMessage(1, this.id, () => this.id.serialize(writer));
      }
      if (this.overlap_id !== undefined) {
        writer.writeRepeatedMessage(2, this.overlap_id, (item: dependency_1.atlas.hdmap.Id) =>
          item.serialize(writer),
        );
      }
      if (this.position !== undefined) {
        writer.writeRepeatedMessage(3, this.position, (item: dependency_2.atlas.hdmap.Curve) =>
          item.serialize(writer),
        );
      }
      if (!w) {
        return writer.getResultBuffer();
      }
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SpeedBump {
      const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes),
        message = new SpeedBump();
      while (reader.nextField()) {
        if (reader.isEndGroup()) {
          break;
        }
        switch (reader.getFieldNumber()) {
          case 1:
            reader.readMessage(
              message.id,
              () => (message.id = dependency_1.atlas.hdmap.Id.deserialize(reader)),
            );
            break;
          case 2:
            reader.readMessage(message.overlap_id, () =>
              pb_1.Message.addToRepeatedWrapperField(
                message,
                2,
                dependency_1.atlas.hdmap.Id.deserialize(reader),
                dependency_1.atlas.hdmap.Id,
              ),
            );
            break;
          case 3:
            reader.readMessage(message.position, () =>
              pb_1.Message.addToRepeatedWrapperField(
                message,
                3,
                dependency_2.atlas.hdmap.Curve.deserialize(reader),
                dependency_2.atlas.hdmap.Curve,
              ),
            );
            break;
          default:
            reader.skipField();
        }
      }
      return message;
    }
    serializeBinary(): Uint8Array {
      return this.serialize();
    }
    static override deserializeBinary(bytes: Uint8Array): SpeedBump {
      return SpeedBump.deserialize(bytes);
    }
  }
}
