// This Source Code Form is subject to the terms of the Mozilla Public
// License, v2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/

/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.1
 * source: map/map_stop_sign.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";

import * as dependency_2 from "./map_geometry";
import * as dependency_1 from "./map_id";

export namespace atlas.hdmap {
  export class StopSign extends pb_1.Message {
    constructor(
      data?:
        | any[]
        | {
            id?: dependency_1.atlas.hdmap.Id;
            stop_line: dependency_2.atlas.hdmap.Curve[];
            overlap_id: dependency_1.atlas.hdmap.Id[];
            type?: StopSign.StopType;
          },
    ) {
      super();
      pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2, 3], []);
      if (!Array.isArray(data) && typeof data == "object") {
        if ("id" in data && data.id != undefined) {
          this.id = data.id;
        }
        this.stop_line = data.stop_line;
        this.overlap_id = data.overlap_id;
        if ("type" in data && data.type != undefined) {
          this.type = data.type;
        }
      }
    }
    get id() {
      return pb_1.Message.getWrapperField(this, dependency_1.atlas.hdmap.Id, 1);
    }
    set id(value: dependency_1.atlas.hdmap.Id) {
      pb_1.Message.setWrapperField(this, 1, value);
    }
    get stop_line() {
      return pb_1.Message.getRepeatedWrapperField(this, dependency_2.atlas.hdmap.Curve, 2);
    }
    set stop_line(value: dependency_2.atlas.hdmap.Curve[]) {
      pb_1.Message.setRepeatedWrapperField(this, 2, value);
    }
    get overlap_id() {
      return pb_1.Message.getRepeatedWrapperField(this, dependency_1.atlas.hdmap.Id, 3);
    }
    set overlap_id(value: dependency_1.atlas.hdmap.Id[]) {
      pb_1.Message.setRepeatedWrapperField(this, 3, value);
    }
    get type() {
      return pb_1.Message.getField(this, 4) as StopSign.StopType;
    }
    set type(value: StopSign.StopType) {
      pb_1.Message.setField(this, 4, value);
    }
    static fromObject(data: {
      id?: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>;
      stop_line: ReturnType<typeof dependency_2.atlas.hdmap.Curve.prototype.toObject>[];
      overlap_id: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>[];
      type?: StopSign.StopType;
    }) {
      const message = new StopSign({
        stop_line: data.stop_line.map((item) => dependency_2.atlas.hdmap.Curve.fromObject(item)),
        overlap_id: data.overlap_id.map((item) => dependency_1.atlas.hdmap.Id.fromObject(item)),
      });
      if (data.id != null) {
        message.id = dependency_1.atlas.hdmap.Id.fromObject(data.id);
      }
      if (data.type != null) {
        message.type = data.type;
      }
      return message;
    }
    toObject() {
      const data: {
        id?: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>;
        stop_line: ReturnType<typeof dependency_2.atlas.hdmap.Curve.prototype.toObject>[];
        overlap_id: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>[];
        type?: StopSign.StopType;
      } = {
        stop_line: this.stop_line.map((item: dependency_2.atlas.hdmap.Curve) => item.toObject()),
        overlap_id: this.overlap_id.map((item: dependency_1.atlas.hdmap.Id) => item.toObject()),
      };
      if (this.id != null) {
        data.id = this.id.toObject();
      }
      if (this.type != null) {
        data.type = this.type;
      }
      return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
      const writer = w || new pb_1.BinaryWriter();
      if (this.id !== undefined) {
        writer.writeMessage(1, this.id, () => this.id.serialize(writer));
      }
      if (this.stop_line !== undefined) {
        writer.writeRepeatedMessage(2, this.stop_line, (item: dependency_2.atlas.hdmap.Curve) =>
          item.serialize(writer),
        );
      }
      if (this.overlap_id !== undefined) {
        writer.writeRepeatedMessage(3, this.overlap_id, (item: dependency_1.atlas.hdmap.Id) =>
          item.serialize(writer),
        );
      }
      if (this.type !== undefined) {
        writer.writeEnum(4, this.type);
      }
      if (!w) {
        return writer.getResultBuffer();
      }
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): StopSign {
      const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes),
        message = new StopSign();
      while (reader.nextField()) {
        if (reader.isEndGroup()) {
          break;
        }
        switch (reader.getFieldNumber()) {
          case 1:
            reader.readMessage(
              message.id,
              () => (message.id = dependency_1.atlas.hdmap.Id.deserialize(reader)),
            );
            break;
          case 2:
            reader.readMessage(message.stop_line, () =>
              pb_1.Message.addToRepeatedWrapperField(
                message,
                2,
                dependency_2.atlas.hdmap.Curve.deserialize(reader),
                dependency_2.atlas.hdmap.Curve,
              ),
            );
            break;
          case 3:
            reader.readMessage(message.overlap_id, () =>
              pb_1.Message.addToRepeatedWrapperField(
                message,
                3,
                dependency_1.atlas.hdmap.Id.deserialize(reader),
                dependency_1.atlas.hdmap.Id,
              ),
            );
            break;
          case 4:
            message.type = reader.readEnum();
            break;
          default:
            reader.skipField();
        }
      }
      return message;
    }
    serializeBinary(): Uint8Array {
      return this.serialize();
    }
    static override deserializeBinary(bytes: Uint8Array): StopSign {
      return StopSign.deserialize(bytes);
    }
  }
  export namespace StopSign {
    export enum StopType {
      UNKNOWN = 0,
      ONE_WAY = 1,
      TWO_WAY = 2,
      THREE_WAY = 3,
      FOUR_WAY = 4,
      ALL_WAY = 5,
    }
  }
}
