// This Source Code Form is subject to the terms of the Mozilla Public
// License, v2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/

/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.1
 * source: map/map_clear_area.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";

import * as dependency_2 from "./map_geometry";
import * as dependency_1 from "./map_id";

export namespace atlas.hdmap {
  export class ClearArea extends pb_1.Message {
    constructor(
      data?:
        | any[]
        | {
            id?: dependency_1.atlas.hdmap.Id;
            overlap_id: dependency_1.atlas.hdmap.Id[];
            polygon?: dependency_2.atlas.hdmap.Polygon;
          },
    ) {
      super();
      pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], []);
      if (!Array.isArray(data) && typeof data == "object") {
        if ("id" in data && data.id != undefined) {
          this.id = data.id;
        }
        this.overlap_id = data.overlap_id;
        if ("polygon" in data && data.polygon != undefined) {
          this.polygon = data.polygon;
        }
      }
    }
    get id() {
      return pb_1.Message.getWrapperField(this, dependency_1.atlas.hdmap.Id, 1);
    }
    set id(value: dependency_1.atlas.hdmap.Id) {
      pb_1.Message.setWrapperField(this, 1, value);
    }
    get overlap_id() {
      return pb_1.Message.getRepeatedWrapperField(this, dependency_1.atlas.hdmap.Id, 2);
    }
    set overlap_id(value: dependency_1.atlas.hdmap.Id[]) {
      pb_1.Message.setRepeatedWrapperField(this, 2, value);
    }
    get polygon() {
      return pb_1.Message.getWrapperField(this, dependency_2.atlas.hdmap.Polygon, 3);
    }
    set polygon(value: dependency_2.atlas.hdmap.Polygon) {
      pb_1.Message.setWrapperField(this, 3, value);
    }
    static fromObject(data: {
      id?: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>;
      overlap_id: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>[];
      polygon?: ReturnType<typeof dependency_2.atlas.hdmap.Polygon.prototype.toObject>;
    }) {
      const message = new ClearArea({
        overlap_id: data.overlap_id.map((item) => dependency_1.atlas.hdmap.Id.fromObject(item)),
      });
      if (data.id != null) {
        message.id = dependency_1.atlas.hdmap.Id.fromObject(data.id);
      }
      if (data.polygon != null) {
        message.polygon = dependency_2.atlas.hdmap.Polygon.fromObject(data.polygon);
      }
      return message;
    }
    toObject() {
      const data: {
        id?: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>;
        overlap_id: ReturnType<typeof dependency_1.atlas.hdmap.Id.prototype.toObject>[];
        polygon?: ReturnType<typeof dependency_2.atlas.hdmap.Polygon.prototype.toObject>;
      } = {
        overlap_id: this.overlap_id.map((item: dependency_1.atlas.hdmap.Id) => item.toObject()),
      };
      if (this.id != null) {
        data.id = this.id.toObject();
      }
      if (this.polygon != null) {
        data.polygon = this.polygon.toObject();
      }
      return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
      const writer = w || new pb_1.BinaryWriter();
      if (this.id !== undefined) {
        writer.writeMessage(1, this.id, () => this.id.serialize(writer));
      }
      if (this.overlap_id !== undefined) {
        writer.writeRepeatedMessage(2, this.overlap_id, (item: dependency_1.atlas.hdmap.Id) =>
          item.serialize(writer),
        );
      }
      if (this.polygon !== undefined) {
        writer.writeMessage(3, this.polygon, () => this.polygon.serialize(writer));
      }
      if (!w) {
        return writer.getResultBuffer();
      }
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ClearArea {
      const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes),
        message = new ClearArea();
      while (reader.nextField()) {
        if (reader.isEndGroup()) {
          break;
        }
        switch (reader.getFieldNumber()) {
          case 1:
            reader.readMessage(
              message.id,
              () => (message.id = dependency_1.atlas.hdmap.Id.deserialize(reader)),
            );
            break;
          case 2:
            reader.readMessage(message.overlap_id, () =>
              pb_1.Message.addToRepeatedWrapperField(
                message,
                2,
                dependency_1.atlas.hdmap.Id.deserialize(reader),
                dependency_1.atlas.hdmap.Id,
              ),
            );
            break;
          case 3:
            reader.readMessage(
              message.polygon,
              () => (message.polygon = dependency_2.atlas.hdmap.Polygon.deserialize(reader)),
            );
            break;
          default:
            reader.skipField();
        }
      }
      return message;
    }
    serializeBinary(): Uint8Array {
      return this.serialize();
    }
    static override deserializeBinary(bytes: Uint8Array): ClearArea {
      return ClearArea.deserialize(bytes);
    }
  }
}
