// This Source Code Form is subject to the terms of the Mozilla Public
// License, v2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/

/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.1
 * source: common/direction.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";

export namespace atlas.common {
    export enum Direction {
        EAST = 0,
        WEST = 1,
        SOUTH = 2,
        NORTH = 3,
        NORTHEAST = 4,
        SOUTHEAST = 5,
        SOUTHWEST = 6,
        NORTHWEST = 7
    }
}
